name: Build Godot Project

on:
  push:
    branches:
      - main

jobs:
  export_web:
    name: Export
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Export Game
        id: export
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
          use_preset_export_path: true
          export_debug: false

      - name: Upload web build to itch
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.BUTLER_KEY }}
          gameData: ./builds/jam/web/Web.zip
          itchUsername: coderaurus
          itchGameId: ld-57
          buildChannel: html5

      - name: Archive the builds
        uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.export.outputs.archive_directory }}/*